name: Python CI
# The workflow name

# Trigger the workflow on specified events
on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    # Specifies the latest Ubuntu runner environment for testing

    steps:
      # 1. Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v2

      # 2. Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. Run tests
      - name: Run tests
        run: pytest
